version: 2
jobs:
    build:

        docker:
          - image: continuumio/anaconda3
        working_directory: /tmp/src
        steps:
          - checkout
          - run:
              command: |
                pip install ./bk_packages
                pytest  --showlocals bk_packages/tests
